---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - pip install uv
      - uv export --group docs --group clients --group flask --no-hashes --output-file requirements.txt
    post_install:
      - pip install .
      - pip install --requirement requirements.txt

sphinx:
  configuration: docs/conf.py
